name: Create a pull request for develop.

on:
  push:
    branches:
      - feature/**
      - fix/**

jobs:
  create-develop-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check if pr exists
        id: check_pr
        run: |
          title=${{ (startsWith(github.ref, 'refs/heads/feature') && 'Feature') || 'Fix' }}
          echo "title=${title}" >> $GITHUB_OUTPUT
      - name: Create pr
        run: gh pr create -B develop -t ${{ steps.check_pr.outputs.title }} --body-file ./.github/pull_request_template.md
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
